version: "3.3"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports: 
      - 8000:8000
    volumes: 
      - ./backend:/app
      - /app/node_modules
    depends_on: 
      - mysql_server
      - redis_server
  
  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=local_db
      - MYSQL_USER=localhost
      - MYSQL_PASSWORD=localhost
      - MYSQL_ROOT_PASSWORD=localhost
    volumes:
      - "./mysql_server/create-local-db.sql:/docker-entrypoint-initdb.d/1.sql"

  redis_server:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./redis_server:/data
